### PR TITLE
Polymorphic through

### PR DESCRIPTION
**Pull request by camertron**
Adds tests for polymorphic through associations for all versions of ActiveRecord, and make changes for ActiveRecord 4.2, which changes the way bind variables are treated.

### CODE REVIEW

**Comment by kenaniah** [comment]
This solves the original test case, but I'm now running into a new regression:

When executing:
```ruby
sub = Location.arel_table.project 1
sub.join(ArelHelpers.join_association(Location, :card_locations))
sub.to_sql
```

The output from v2.1.1 (this PR) will be:
```
RuntimeError: unsupported: String
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:735:in `unsupported'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:575:in `visit_Arel_Nodes_StringJoin'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:794:in `block in inject_join'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each_with_index'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `inject'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `inject_join'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:561:in `visit_Arel_Nodes_JoinSource'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:248:in `visit_Arel_Nodes_SelectCore'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:210:in `block in visit_Arel_Nodes_SelectStatement'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:209:in `each'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:209:in `inject'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:209:in `visit_Arel_Nodes_SelectStatement'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:7:in `accept'
	from /Users/kenaniah/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/tree_manager.rb:29:in `to_sql'
	from (irb):3
```

Output from v2.1.0 will be:
```sql
SELECT 1 
FROM "locations" 
INNER JOIN INNER JOIN "card_locations" ON "card_locations"."location_id" = "locations"."id"
```
(Inner join shows up twice)

Expected output:
```sql
SELECT 1 
FROM "locations" 
INNER JOIN "card_locations" ON "card_locations"."location_id" = "locations"."id"
```
---
 
Is this an issue, or am I misusing the API?

**Comment by camertron** [comment]
Ok I'll take a look.

**Comment by camertron** [comment]
Alright @kenaniah, I think this is because you're using `.arel_table`, which brings you into Arel land. Everything in Arel land must be an AST node, and `.join_association` under Rails 4.2 returns a string. Instead of `.arel_table.project`, you could try using `.select` and `.joins`:

```ruby
sub = Location.select(1)
sub.joins(ArelHelpers.join_association(Location, :card_locations))
sub.to_sql
```

This should produce:

```sql
SELECT 1
FROM "locations"
INNER JOIN "card_locations" ON "card_locations"."location_id" = "locations"."id"
```

**Comment by pabuisson** [comment]
I was having the same issue

**Comment by camertron** [comment]
Released v2.2.0.

**Pull request merged**
