### PR TITLE
QueryBuilder#reflect creates shallow copy of builder

### PR DESCRIPTION
**Pull request by wycleffsean**

### CODE REVIEW

**Comment by camertron** [comment]
Hey @wycleffsean, could you provide a few more details? Why this is necessary?

**Comment by wycleffsean** [comment]
Sorry, pretty lazy for me to not provide a description! `#dup` preserves instance variables which can be useful in a couple of scenarios.

It's sometimes nice for the builder class to receive params directly from the controller

```rb
class PostQueryBuilder < ArelHelpers::QueryBuilder
  attr_reader :params

  def initialize(params)
    @params = params
    @query = Post.all
  end

  def with_paging
    limit = params[:per_page]
    offset = params[:page] * limit - limit
    reflect(query.limit(limit).offset(offset))
  end
end

# PostsController
def index
  builder = PostQueryBuilder.new(params)
  @presenter = PostsPresenter.new(builder)
end
```

Another use is when you need idempotent methods

```rb
class PostQueryBuilder < ArelHelpers::QueryBuilder
  def with_comments_count
    reflect(
      with_comments.query.select([Post[Arel.star], Arel.star.count.as('comments_count')])
    )
  end

  def with_comments
     return self if defined?(@with_comments)
     @with_comments = true
     
     # adding this join twice produces invalid SQL
     reflect(
       query.joins(ArelHelpers.join_association(Post, :comments, Arel::Nodes::OuterJoin))
     )
end

builder = PostQueryBuilder.new

# it would be weird for a consumer of the class 
# if either of the following produced an error
builder.with_comments_count
builder.with_comments.with_comments_count
```

**Comment by camertron** [comment]
Good enough for me, thanks @wycleffsean :)

**Comment by camertron** [comment]
Published in v2.5.0.

**Pull request merged**
