### PR TITLE
Join alias helper and ability to alias join associations

### PR DESCRIPTION
**Pull request by camertron**
This PR addresses #14 and introduces two new bits of functionality:
- Table alias helper.
  Include `ArelHelpers::Aliases` in your models to add the `#aliased_as` method. For example:

``` ruby
Post.aliased_as(:first_post) do |first_post|
  first_post  # instance of Arel::Nodes::TableAlias
end
```
- Ability to specify aliases when constructing join associations:

``` ruby
Comment.aliased_as(:opinions) do |opinions|
  Favorite.aliased_as(:faves) do |faves|
    Post.joins(
      ArelHelpers.join_association(
        Post, [:comments, :favorites], Arel::Nodes::InnerJoin, aliases: [opinions, faves]
      )
    )
  end
end
```

Is this what you had in mind, @graudeejs?

### CODE REVIEW

**Comment by graudeejs** [comment]
Sorry for long delay.

Hopefully I'll have time to test this today or Sunday.
I have a project with implements this kind of functionality, but I'd like to replace it with ArelHelpers. The tests will reveal, weather everything is OK or not - I've got tests there for every single possible scenario I could Imagine.

**Comment by graudeejs** [comment]
Looks like I'll be busy for some time....
From you example it looks OK, even better when I checked source code.

Unfortunately I'm having lack of spare time, and I checked the project where I wanted to use arel-helpers... It might take entire day to refactor code.

So It looks good, but I can't confirm, that it works for my use-case (It probably does).
Up to you weather to wait till I have more time, or accept this pull request.

Sorry for trouble.

**Comment by camertron** [comment]
That's ok @graudeejs, let me know when you have tjme to look at it.

**Comment by camertron** [comment]
Any update on this @graudeejs?

**Comment by graudeejs** [comment]
Sorry @camertron. I'm all over with work since I changed my workplace.
Looks like I'll have spare time only at new year weekend.

**Comment by myxaluch** [comment]
Hello, @camertron! 
We faced up with same needs in our project, and It would be great, if you commit this PR. 
I can help you with conflicts and add support for `join_association_5_0`)

**Comment by camertron** [comment]
Released as v2.6.0. Happy databasing!

**Pull request merged**
