### PR TITLE
support Rails 5.0

### PR DESCRIPTION
**Pull request by vkill**

### CODE REVIEW

**Comment by camertron** [comment]
LGTM, thanks @vkill :) #OSSPower

**Comment by camertron** [comment]
Ok, hang on @vkill. I just tried to run tests using Rails 5 and your PR has introduced a test failure (looks like I merged a little too fast). I have reverted the PR. I'll try to take a look at what went wrong, but if you have any ideas, please submit another PR. Thanks :)

**Comment by camertron** [comment]
Ok, I found the issue and have submitted [this pull request](https://github.com/camertron/arel-helpers/pull/26). Mind taking a look @vkill? Thanks for your help on this.

**Comment by vkill** [comment]
@camertron oh, I found that my join_association.rb is very old. thank you fast feedback :)

**Pull request merged**
